"""One-shot dialog that displays a fresh recovery code.

The token is generated by the caller (so the same dialog can be used for
first-run auto-generation AND for "regenerate" from Advanced). The dialog
makes clear the code will not be shown again, and offers an easy
copy-to-clipboard. We deliberately make the user click "I have saved the
code" to dismiss so they don't lose it by mis-clicking.
"""
from __future__ import annotations

from PyQt6.QtCore import Qt
from PyQt6.QtGui import QGuiApplication, QPixmap
from PyQt6.QtWidgets import (
    QDialog,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QVBoxLayout,
)

from brake.branding import APP_NAME
from brake.gui.assets import brake_path


class RecoveryDialog(QDialog):
    def __init__(self, token: str, parent=None) -> None:
        super().__init__(parent)
        self.setWindowTitle(f"{APP_NAME} - Recovery code")
        self.setMinimumWidth(560)
        # Hard to dismiss by accident: no close button, no Esc.
        self.setWindowFlag(Qt.WindowType.WindowCloseButtonHint, False)
        self.setWindowFlag(Qt.WindowType.WindowContextHelpButtonHint, False)

        root = QVBoxLayout(self)
        root.setContentsMargins(28, 24, 28, 24)
        root.setSpacing(16)

        # Brand row: lock + headline together so it feels like a moment, not a popup.
        head_row = QHBoxLayout()
        head_row.setSpacing(14)
        logo = QLabel()
        pix = QPixmap(brake_path("base", 32)).scaled(
            40, 40,
            Qt.AspectRatioMode.KeepAspectRatio,
            Qt.TransformationMode.FastTransformation,
        )
        logo.setPixmap(pix)
        logo.setFixedSize(40, 40)
        head_row.addWidget(logo, 0, Qt.AlignmentFlag.AlignVCenter)

        title = QLabel("Save this code somewhere safe.")
        title.setObjectName("RecoveryTitle")
        head_row.addWidget(title, 1, Qt.AlignmentFlag.AlignVCenter)
        root.addLayout(head_row)

        explainer = QLabel(
            f"This code can reset your password immediately. It can also start "
            f"a 15-minute emergency cooldown before {APP_NAME} turns off if "
            "you get stuck behind a commitment.\n\n"
            "You will not see it again. Do not save it somewhere easy to reach "
            "on this computer. Write it on paper, take a photo on your phone, "
            "or give it to someone you trust. If you want the strongest "
            "commitment, you can choose not to copy it, but then a forgotten "
            "password may require a full reset."
        )
        explainer.setWordWrap(True)
        explainer.setObjectName("RecoveryBody")
        root.addWidget(explainer)

        token_row = QHBoxLayout()
        token_row.setSpacing(8)
        self.token_field = QLineEdit(token)
        self.token_field.setReadOnly(True)
        self.token_field.setObjectName("RecoveryToken")
        self.token_field.setCursorPosition(0)
        token_row.addWidget(self.token_field, 1)
        self.copy_btn = QPushButton("Copy")
        self.copy_btn.setObjectName("SecondaryButton")
        self.copy_btn.clicked.connect(self._copy)
        token_row.addWidget(self.copy_btn)
        root.addLayout(token_row)

        warn = QLabel(
            "Anyone with this code can reset your password or schedule "
            "emergency disable on this machine. Treat it like a password, "
            "but keep it away from impulse access."
        )
        warn.setWordWrap(True)
        warn.setObjectName("RecoveryWarn")
        root.addWidget(warn)

        button_row = QHBoxLayout()
        button_row.addStretch(1)
        self.ok_btn = QPushButton("I understand")
        self.ok_btn.setObjectName("PrimaryButton")
        self.ok_btn.clicked.connect(self.accept)
        button_row.addWidget(self.ok_btn)
        root.addLayout(button_row)

    def _copy(self) -> None:
        QGuiApplication.clipboard().setText(self.token_field.text())
        self.copy_btn.setText("Copied")

    def keyPressEvent(self, event) -> None:  # type: ignore[override]
        # Block Esc so the user clicks the explicit confirm button.
        if event.key() == Qt.Key.Key_Escape:
            event.ignore()
            return
        super().keyPressEvent(event)
